# Generated by Django 5.1.2 on 2024-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Id', models.CharField(max_length=20, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('rfid_Tag', models.CharField(max_length=100, unique=True)),
                ('parent_Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
