# Generated by Django 5.1.2 on 2024-11-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_In', models.DateTimeField(auto_now_add=True)),
                ('check_Out', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_details.student')),
            ],
        ),
    ]
