# Generated by Django 5.1.2 on 2025-03-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_details', '0002_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='check_In',
            new_name='check_in_time',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='check_Out',
            new_name='check_out_time',
        ),
    ]
